### ISSUE TITLE
Release version 2.4 on NuGet

### ISSUE THREAD

**Issue by monerofglory** [kesac/Syllabore#12]
**Problem Space**
I recently wanted to demonstrate a release version of Syllabore to a friend, but noticed that the latest version on NuGet was 2.3.1 released on October 11th 2023. There have since been many commits/features added!

**What is your idea?**
If you still wish to release your package via NuGet (the prerogative of the maintainer, of course), you should release a new version for use, especially with your new .NET 8 changes.

If you do not desire to maintain packages on NuGet, feel free to close this issue.

**How will this benefit users of Syllabore?**
- [x] It allows users to access up-to-date features and improvements.

**Comment by kesac** [comment]
I agree! I've been meaning to get a new NuGet package out so the API documentation would start surfacing in IDEs. v2.3.2 is now released [here](https://github.com/kesac/Syllabore/releases/tag/v2.3.2) and made available via [NuGet](https://www.nuget.org/packages/Syllabore).
