### ISSUE TITLE
Inject random generator 

### ISSUE THREAD

**Issue by tmx7777** [kesac/Syllabore#14]
I propose that all classes that use `System.Random` should provide a constructor overload that allows a `Random` instance to be injected by the caller.

This would allow the caller to create a random generator with a specific seed. This is helpful when creating test data that is always the same based on that seed. For example that would be the case, if one uses NUnit's random generator which is derived from`Random` and seeded individually for each test case.

Alternatively it could be injected as `Func<int>` or as an interface.

**Comment by kesac** [comment]
I agree, this will be useful. `Random` instantiation occurs in the constructors of [NameGenerator](https://github.com/kesac/Syllabore/blob/ace1e3141c1a183e1626e4c17ee85e069b4c5984/Syllabore/Syllabore/NameGenerator.cs#L140), [SyllableGenerator](https://github.com/kesac/Syllabore/blob/ace1e3141c1a183e1626e4c17ee85e069b4c5984/Syllabore/Syllabore/SyllableGenerator.cs#L305), [TransformerSet](https://github.com/kesac/Syllabore/blob/ace1e3141c1a183e1626e4c17ee85e069b4c5984/Syllabore/Syllabore/TransformSet.cs#L59), and [DefaultNameTransformer](https://github.com/kesac/Syllabore/blob/ace1e3141c1a183e1626e4c17ee85e069b4c5984/Syllabore/Syllabore/DeprecatedDefaultNameTransformer.cs#L27) which isn't a lot to overload.

There is also a static class, [ListExtensions](https://github.com/kesac/Syllabore/blob/ace1e3141c1a183e1626e4c17ee85e069b4c5984/Syllabore/Syllabore/ListExtensions.cs#L14), that keeps a static `Random` instance for its extension methods. I'll look at getting rid of it and reworking the extension methods so there can be more control over `Random`.

**Comment by kesac** [comment]
New changes in upcoming version v2.3.3:
- Generator classes that simulate randomness now implement `IRandomizable`
- The instance of `System.Random` within generator classes is now accessible through the `Random` property
   - This affects `NameGenerator`, `SyllableGenerator`, `SyllableSet`, and `TransformSet` 
- In addition, a new fluent-style method has been added to each generator class to set the `Random` instance during configuration
- The wiki page [here](https://github.com/kesac/Syllabore/wiki/Guide-2.4%EA%9E%89-Random-Seeds) has been added and contains code examples on controlling random seeds (through the property or through the fluent methods)

I ended up skipping adding more constructor overloads, but not against it in the future if controlling seeds becomes a common activity.

**Comment by kesac** [comment]
v2.3.3 is now published on NuGet.org and GitHub
