### ISSUE TITLE
Documentation for .Invalidate

### ISSUE THREAD

**Issue by nallware** [kesac/Syllabore#2]
In the latest stable  NuGet version 1.1.0, .Invalidate gives Compiler error: 'NameValidator' does not contain a definition for 'Invalidate' and no accessible extension method 'Invalidate' accepting a first argument of type 'NameValidator' could be found (are you missing a using directive or an assembly reference?)

I switched to .DoNotAllowPattern but wanted to note this for the documentation.  Also thanks for Syllabore! It's extremely useful!

**Comment by kesac** [comment]
@nallware Sorry you ran into that and thanks for letting me know! I've updated the quick start documentation to use the correct method name.
