### ISSUE TITLE
[Feature Request] More Examples

### ISSUE THREAD

**Issue by marcgrabow** [kesac/Syllabore#4]
Hey kesac,

Syllabore is a fantastic tool and works great, thanks a lot for creating it!

I'm having a hard time coming up with the right settings for specific requirements (lack of knowledge how language actually works) and was wondering if you (or someone else) is planning on adding more basic examples to help people getting a generator up and running? The examples that are already in the repo are great but a few more would be even better :)

Some ideas:
* First name
* Surname
* Space ship name
* Planet name
* Animal name
* Weapon name
* ...

**Comment by kesac** [comment]
@marcgrabow thank you for the feedback! I will take a look at populating the examples project with more stuff and authoring 2 or 3 additional guides for the wiki. 

To start things off, I've drafted a guide [here](https://github.com/kesac/Syllabore/wiki/Guide-1:-Spaceships) to address how spaceship names might be generated by Syllabore. 

I will leave this issue open until I've gotten more guides out.

**Comment by kesac** [comment]
Update: 
- Added new guide for planets [here](https://github.com/kesac/Syllabore/wiki/Guide-1:-Planets)
- Moved guide for spaceships to [here](https://github.com/kesac/Syllabore/wiki/Guide-2:-Spaceships)

**Comment by kesac** [comment]
Thanks @marcgrabow! If you start using the guides, don't hesitate to let me know if they are too complicated, missing explanations, etc. For now, my plan is to just tackle an item from your list one at a time.  Let me know if you want a specific guide that will help you with your game.

And absolutely, let me know when your game is available and I would love to play!

**Comment by kesac** [comment]
The [wiki](https://github.com/kesac/Syllabore/wiki) has recently been overhauled with the advent of version 2.2.1. There are a lot more examples now beyond the two originally added under this request. I think it's safe to close this request now.
