### ISSUE TITLE
Add Contribution Framework

### ISSUE THREAD

**Issue by monerofglory** [kesac/Syllabore#5]
I think this project would benefit with a way to get in touch to make contributions towards this public repository.

For example, I would like to contribute some Unit Test refactorings that I have made to the NameGeneratorTests.cs. How can we get in touch to request permission from you and permissions within GitHub to open a PR with changes for you to review.

**Comment by kesac** [comment]
Thanks for this suggestion! I'll get some contribution guidelines going plus a basic PR template.

**Comment by kesac** [comment]
- New contributing.md added through #6
- New PR template + issues templates added
